/*
 * generated by Xtext
 */
package org.pnml.tools.epnk.pntypes.hlpngs.datatypes.concretesyntax.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class HLPNGInscriptionLanguageUiModule extends org.pnml.tools.epnk.pntypes.hlpngs.datatypes.concretesyntax.ui.AbstractHLPNGInscriptionLanguageUiModule {
	public HLPNGInscriptionLanguageUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
