<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="hlpnginscriptiondocument"
    nsURI="http://org.pnml.tools/epnk/types/hlpngs/datatypes/hlpnginscriptiondocument"
    nsPrefix="hlpngid">
  <eClassifiers xsi:type="ecore:EClass" name="HLPNGInscriptionDocument">
    <eStructuralFeatures xsi:type="ecore:EReference" name="declarations" upperBound="-1"
        eType="ecore:EClass ../../org.pnml.tools.epnk.pntypes.hlpngs.datatypes/model/HLPNGDataTypes.ecore#//terms/Declarations"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="term" upperBound="-1" eType="ecore:EClass ../../org.pnml.tools.epnk.pntypes.hlpngs.datatypes/model/HLPNGDataTypes.ecore#//terms/Term"
        containment="true"/>
  </eClassifiers>
</ecore:EPackage>
