/*
* generated by Xtext
*/
package org.pnml.tools.epnk.pntypes.hlpngs.datatypes.concretesyntax.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.pnml.tools.epnk.pntypes.hlpngs.datatypes.concretesyntax.services.HLPNGInscriptionLanguageGrammarAccess;

public class HLPNGInscriptionLanguageParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private HLPNGInscriptionLanguageGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected org.pnml.tools.epnk.pntypes.hlpngs.datatypes.concretesyntax.parser.antlr.internal.InternalHLPNGInscriptionLanguageParser createParser(XtextTokenStream stream) {
		return new org.pnml.tools.epnk.pntypes.hlpngs.datatypes.concretesyntax.parser.antlr.internal.InternalHLPNGInscriptionLanguageParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Document";
	}
	
	public HLPNGInscriptionLanguageGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(HLPNGInscriptionLanguageGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
