/*
* generated by Xtext
*/
package org.pnml.tools.epnk.pntypes.hlpngs.datatypes.concretesyntax.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class HLPNGInscriptionLanguageAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("org/pnml/tools/epnk/pntypes/hlpngs/datatypes/concretesyntax/parser/antlr/internal/InternalHLPNGInscriptionLanguage.tokens");
	}
}
