/*
* generated by Xtext
*/
package org.pnml.tools.epnk.pntypes.hlpngs.datatypes.concretesyntax.ui.contentassist;

import org.pnml.tools.epnk.pntypes.hlpngs.datatypes.concretesyntax.ui.contentassist.AbstractHLPNGInscriptionLanguageProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class HLPNGInscriptionLanguageProposalProvider extends AbstractHLPNGInscriptionLanguageProposalProvider {

}
