/*
 * generated by Xtext
 */
package org.pnml.tools.epnk.pntypes.hlpngs.datatypes.concretesyntax;

import org.eclipse.xtext.conversion.IValueConverterService;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class HLPNGInscriptionLanguageRuntimeModule extends org.pnml.tools.epnk.pntypes.hlpngs.datatypes.concretesyntax.AbstractHLPNGInscriptionLanguageRuntimeModule {

	// @generated NOT
	// @author eki
    // Value Converter for NAT
    @Override
    public Class<? extends IValueConverterService> bindIValueConverterService() {
        return HLPNGValueConverter.class;
    }
}
