<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="arbitrarydeclarations"
    nsURI="http://org.pnml.tools/epnk/types/hlpngs/datatypes/arbitrarydeclarations"
    nsPrefix="arbitrarydeclarations">
  <eClassifiers xsi:type="ecore:EClass" name="ArbitrarySort" eSuperTypes="HLPNGDataTypes.ecore#//terms/SortDecl"/>
  <eClassifiers xsi:type="ecore:EClass" name="ArbitraryOperator" eSuperTypes="HLPNGDataTypes.ecore#//terms/OperatorDecl">
    <eStructuralFeatures xsi:type="ecore:EReference" name="input" upperBound="-1"
        eType="ecore:EClass HLPNGDataTypes.ecore#//terms/Sort" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="output" lowerBound="1"
        eType="ecore:EClass HLPNGDataTypes.ecore#//terms/Sort" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Unparsed" eSuperTypes="HLPNGDataTypes.ecore#//terms/Declaration">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="contents" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
