/*
 * generated by Xtext
 */
package org.pnml.tools.epnk.pntypes.hlpngs.datatypes.concretesyntax.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import org.pnml.tools.epnk.pntypes.hlpngs.datatypes.concretesyntax.ui.internal.HLPNGInscriptionLanguageActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class HLPNGInscriptionLanguageExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return HLPNGInscriptionLanguageActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return HLPNGInscriptionLanguageActivator.getInstance().getInjector(HLPNGInscriptionLanguageActivator.ORG_PNML_TOOLS_EPNK_PNTYPES_HLPNGS_DATATYPES_CONCRETESYNTAX_HLPNGINSCRIPTIONLANGUAGE);
	}
	
}
