/*
* generated by Xtext
*/
package org.pnml.tools.epnk.pntypes.hlpngs.datatypes.concretesyntax.ui.outline;

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;

/**
 * customization of the default outline structure
 * 
 */
public class HLPNGInscriptionLanguageOutlineTreeProvider extends DefaultOutlineTreeProvider {
	
}
