<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="signalnets"
    nsURI="http://org.pnml.tools/epnk/types/signalnets" nsPrefix="sinet">
  <eClassifiers xsi:type="ecore:EClass" name="SignalNet" eSuperTypes="../../org.pnml.tools.epnk/model/PNMLCoreModel.ecore#//PetriNetType"/>
  <eClassifiers xsi:type="ecore:EClass" name="Place" eSuperTypes="../../org.pnml.tools.epnk/model/PNMLCoreModel.ecore#//Place">
    <eStructuralFeatures xsi:type="ecore:EReference" name="marking" eType="#//Marking"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Arc" eSuperTypes="../../org.pnml.tools.epnk/model/PNMLCoreModel.ecore#//Arc">
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="#//ArcType"
        containment="true" eOpposite="#//ArcType/arc"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Marking" eSuperTypes="../../org.pnml.tools.epnk/model/PNMLCoreModel.ecore#//Attribute">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="text" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//NonNegativeInteger"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ArcType" eSuperTypes="../../org.pnml.tools.epnk/model/PNMLCoreModel.ecore#//Attribute">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="text" eType="#//ArcTypes"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="arc" eType="#//Arc" transient="true"
        eOpposite="#//Arc/type"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ArcTypes">
    <eLiterals name="read" value="1" literal="read"/>
    <eLiterals name="inhibit" value="2"/>
  </eClassifiers>
</ecore:EPackage>
