<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="geditor"
    nsURI="http://geditor/1.0" nsPrefix="geditor">
  <eClassifiers xsi:type="ecore:EClass" name="Geometry">
    <eStructuralFeatures xsi:type="ecore:EReference" name="GeometryObjects" upperBound="-1"
        eType="#//GObject" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="globalAppearancePath" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GObject">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="appearancePath" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Point" eSuperTypes="#//GObject">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="x" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="y" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="z" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Arc" eSuperTypes="#//GObject">
    <eStructuralFeatures xsi:type="ecore:EReference" name="start" lowerBound="1" eType="#//Point"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="end" lowerBound="1" eType="#//Point"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="controlPoints" upperBound="-1"
        eType="#//Point" containment="true"/>
  </eClassifiers>
</ecore:EPackage>
