<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="parserrules"
    nsURI="http://org.pnml.tools/epnk/helpers/parserrules/1.0" nsPrefix="parserrules">
  <eClassifiers xsi:type="ecore:EClass" name="Rules">
    <eStructuralFeatures xsi:type="ecore:EReference" name="rule" upperBound="-1" eType="#//Rule"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" upperBound="-1" eType="#//ClassRef"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="feature" upperBound="-1"
        eType="#//Feature" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="maxprio" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="token" upperBound="-1"
        eType="#//Token" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Rule" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="context" eType="#//ClassRef"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Iterator" eSuperTypes="#//Rule">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lower" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="0"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="upper" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="#//ClassRef"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rule" lowerBound="1" eType="#//Rule"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="first" eType="#//Token"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sep" eType="#//Token"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="last" eType="#//Token"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="feature" eType="#//Feature"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ClassRef">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="package" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Feature">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Choice" eSuperTypes="#//Rule">
    <eStructuralFeatures xsi:type="ecore:EReference" name="alternative" upperBound="-1"
        eType="#//Rule" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="#//ClassRef"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Op" eSuperTypes="#//Rule">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lower" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="upper" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="prio" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="#//ClassRef"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="feature" upperBound="-1"
        eType="#//Feature"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="assoc" eType="#//OpType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="symbol" eType="#//Token"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Atom" eSuperTypes="#//Rule">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="prio" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="def" lowerBound="1" eType="#//Rule"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="first" eType="#//Token"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="last" eType="#//Token"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="OpType">
    <eLiterals name="none"/>
    <eLiterals name="left" value="1"/>
    <eLiterals name="right" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Token">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="text" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="separator" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parenthesis" eType="#//Parenthesis"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="breakafter" lowerBound="1"
        eType="#//LinebreakCategory"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="breakbefore" lowerBound="1"
        eType="#//LinebreakCategory"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="seperatorblanks" eType="#//Separator"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Sequence" eSuperTypes="#//Rule">
    <eStructuralFeatures xsi:type="ecore:EReference" name="sequence" upperBound="-1"
        eType="#//Rule"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Element" eSuperTypes="#//Rule">
    <eStructuralFeatures xsi:type="ecore:EReference" name="feature" lowerBound="1"
        eType="#//Feature"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="#//ClassRef"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Symbol" eSuperTypes="#//Rule">
    <eStructuralFeatures xsi:type="ecore:EReference" name="token" lowerBound="1" eType="#//Token"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="LinebreakCategory">
    <eLiterals name="over"/>
    <eLiterals name="end" value="1"/>
    <eLiterals name="middle" value="2"/>
    <eLiterals name="start" value="3"/>
    <eLiterals name="always" value="4"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Parenthesis" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Open" eSuperTypes="#//Parenthesis">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="tabulate" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="absolute" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="offset" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Close" eSuperTypes="#//Parenthesis"/>
  <eClassifiers xsi:type="ecore:EClass" name="Separator">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="blankbefore" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="blankafter" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Conditional" eSuperTypes="#//Rule">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="class" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="thenCase" eType="#//Rule"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="elseCase" eType="#//Rule"/>
  </eClassifiers>
</ecore:EPackage>
